article/urls.py
from django.urls import path

from . import views

app_name = 'article'
urlpatterns = [
    path('', views.Homepage, name='homepage'),
    path('article_list/', views.aricle_list, name='article_list'),
    path('article_detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article_create/', views.article_create, name='article_create'),
    path('article_delete/<int:id>/', views.article_delete, name='article_delete'),
    path('article_update/<int:id>/', views.article_update, name='article_update'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('article.urls')),
    path('admin/', admin.site.urls),
    path('userprofile/', include('userprofile.urls')),
    path('comment/', include('comment.urls')),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.user_register, name='signup'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, default='社会')

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100, default='热点')

    def __str__(self):
        return self.name


class ArticlePost(models.Model):
    # 文章作者。参数 on_delete 用于指定数据删除的方式，避免两个关联表的数据不一致。
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # 文章标题。models.CharField 为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=100)

    # 文章正文。保存大量文本使用 TextField
    body = models.TextField()

    # 文章创建时间。参数 default=timezone.now 指定其在创建数据时将默认写入当前的时间
    created_time = models.DateTimeField(default=timezone.now)

    total_views = models.PositiveIntegerField(default=0)

    # 分类用外键，即一篇文章只能对应分类，但一个分类下可以有多篇文章
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    # 标签采用多对多，即一篇文章可以有多个标签，一个标签下也有多篇文章
    tags = models.ManyToManyField(Tag, blank=True)

    class Meta:
        ordering = ('-created_time',)

    def __str__(self):
        return self.title

    # 获取文章地址
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

article/forms.py
from django import forms
from .models import ArticlePost

#Article's forms
class ArticlePostForm(forms.ModelForm):
    class Meta:
        #指明数据模型来源
        model = ArticlePost
        #define fields
        fields = ('title', 'body')

article/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.http import HttpResponse
from article import models
from .forms import ArticlePostForm
from comment.models import Comment
from django.contrib.auth.models import User
import markdown
from comment.forms import CommentForm


# Create your views here.
def Homepage(request):
    return render(request, 'article/myblog.html')

def aricle_list(request):
    if request.GET.get('order') == 'total_views':
        article_list = models.ArticlePost.objects.all().order_by('-total_views')
        order = 'total_views'
    else:
        article_list = models.ArticlePost.objects.all()
        order = 'normal'
    paginator = Paginator(article_list, 3)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    context = {'articles': articles, 'order':order}
    return render(request, 'article/list.html', context)

def article_detail(request, id):
    article = models.ArticlePost.objects.get(id=id)

    # 取出文章评论
    comments = Comment.objects.filter(article=id)

    # 浏览量 +1
    article.total_views += 1
    article.save(update_fields=['total_views'])

    #将markdown语法渲染成html样式
    article.body = markdown.markdown(article.body,
         extensions=[
             # 包含 缩写、表格等常用扩展
             'markdown.extensions.extra',
             # 语法高亮扩展
             'markdown.extensions.codehilite',
         ])
    content = {'article': article, 'comments': comments}
    return render(request, 'article/detail.html', content)

def article_create(request):
    #用户提交数据
    if request.method == "POST":
        #将提交的数据赋值给表单实例
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=1)
            #将新文章保存至数据库
            new_article.save()
            return redirect("article:article_list")
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    #用户请求数据
    else:
        #创建表单类实例
        article_post_form = ArticlePostForm()
        content = {'article_post_form': article_post_form}
        return render(request, 'article/create.html', content)


def article_delete(request,id):
    article = models.ArticlePost.objects.get(id=id)
    article.delete()
    return redirect("article:article_list")


@login_required(login_url='/userprofile/login/')
def article_update(request, id):
    #获取需要修改的文章对象
    article = models.ArticlePost.objects.get(id=id)
    if request.method=="POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            return redirect("article:article_detail", id=id)
        else:
            return HttpResponse("表单内容有误，请重新填写")
    else:
        article_post_form = ArticlePostForm()
        # 赋值上下文，将 article 文章对象也传递进去，以便提取旧的内容
        context = {'article': article, 'article_post_form': article_post_form}
        return render(request, 'article/update.html', context)

article/templates/base.html
<!--{% load staticfiles %}-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bruce's Blog</title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/blog.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/grid.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/navbars.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/carousel.css' %}" rel="stylesheet">
    <link href="{% static 'md_css/monokai.css' %}" rel="stylesheet">
</head>
<body>
    {% include 'header.html' %}

    {% block content %}
    {% endblock content %}

    {% include 'footer.html' %}

    <script src="{% static 'popper/popper.js' %"></script>
    <script src="{% static 'jquery/jquery.js' %"></script>
    <script src="{% static 'layer/layer.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %"></script>
</body>
</html>

article/templates/footer.html
{% load staticfiles %}
<footer class="blog-footer">
  <p>Bruce Wang's Blog | template built for
    <a href="https://getbootstrap.com/">Bootstrap</a> by
    <a href="https://twitter.com/mdo">@mdo</a> |
    Copyright@2020
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

article/templates/header.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'article:homepage' %}">新闻</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExample04">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'article:article_list' %}">文章列表</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'article:article_create' %}">发表文章</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-md-0">
        {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="btn btn-outline-success mr-sm-2" href="#">{{ user.username }}</a>
                <div class="dropdown-menu " aria-labelledby="navbarDropdown">
                    <a class="dropdown-item btn-sm" href="{% url 'userprofile:logout' %}">退出登录</a>
                </div>
            </li>
        {% else %}
            <a class="btn btn-outline-success mr-sm-2" href="{% url 'userprofile:login' %}">登录</a>
        {% endif %}
        <a class="btn btn-outline-success mr-sm-2" href="{% url 'userprofile:signup' %}">注册</a>
        <input class="form-control mr-sm-2" type="text" placeholder="搜索" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
    </form>
  </div>
</nav>